### ISSUE TITLE
Databricks notebook issue

### ISSUE THREAD

**Issue by mohan3d** [tink-crypto/tink-java#20]
Environment:
Databricks notebook
Java: 1.8.0_382 (Azul Systems, Inc.)
scala: version 2.12.15
Tink: 1.12.0 (I tried 1.7.0 as well, same issue)

Issue:
I was able to encrypt/decrypt with no issues locally, then I got this issue when I tried to run on the notebook.
![image](https://github.com/tink-crypto/tink-java/assets/14618484/2e4c657d-7992-4d43-9bc0-8b49c7451c8b)

```
ERROR Uncaught throwable from user code: java.lang.NoClassDefFoundError: Could not initialize class com.google.crypto.tink.aead.AeadConfig
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2321796732942202:4)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2321796732942202:48)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$$iw$$iw$$iw$$iw.<init>(command-2321796732942202:50)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$$iw$$iw$$iw.<init>(command-2321796732942202:52)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$$iw$$iw.<init>(command-2321796732942202:54)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$$iw.<init>(command-2321796732942202:56)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read.<init>(command-2321796732942202:58)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$.<init>(command-2321796732942202:62)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$read$.<clinit>(command-2321796732942202)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$eval$.$print$lzycompute(<notebook>:7)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$eval$.$print(<notebook>:6)
	at $line0deef6ce60e84e46bd193cc337630cdb38.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:223)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:236)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1489)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:1442)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:236)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$34(DriverLocal.scala:1083)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:41)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:99)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$22(DriverLocal.scala:1066)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:426)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:216)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:424)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:418)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:85)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:472)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:455)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:85)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:1003)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:741)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:733)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:642)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:687)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:519)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:435)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:277)
	at java.lang.Thread.run(Thread.java:750)
```

Dependency:
![image](https://github.com/tink-crypto/tink-java/assets/14618484/f1211c88-1bb4-4392-ba09-c6df5e15bf42)

**Comment by juergw** [comment]
I think AeadConfig is just the first class of Tink that gets loaded. So it seems that you are missing the dependency on Tink. Can you check if you follow all the steps from
https://developers.google.com/tink/tink-setup#java?

**Comment by mohan3d** [comment]
Thanks @juergw the issue turned out to be on Spark side. there is a conflict between protobuf provided by Spark and the one of Tink. 

My temporary solution was to shade protobuf to avoid the conflict as I have no control over Spark.

I will proceed closing this ticket.
